Machine.add(me.dir()+"constants/Constants.ck");
Machine.add(me.dir()+"actions/payloads/PayloadBase.ck");
Machine.add(me.dir()+"actions/payloads/MidiNoteCreatePayload.ck");
Machine.add(me.dir()+"dispatcher/DispatchMessage.ck");
Machine.add(me.dir()+"dispatcher/dispatchables/DispatchableBase.ck");
Machine.add(me.dir()+"dispatcher/Dispatcher.ck");
Machine.add(me.dir()+"dispatcher/AppDispatcher.ck");
Machine.add(me.dir()+"actions/MidiNoteActions.ck");
Machine.add(me.dir()+"models/MidiNote.ck");
